# Generated by Django 3.1.6 on 2024-05-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0002_auto_20240530_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refreshToken',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tokenMaxTime',
            field=models.IntegerField(default=3600),
        ),
    ]
