# Generated by Django 3.1.6 on 2024-06-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0004_user_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastPlaylist',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tokenRequestTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
