# Generated by Django 4.2.20 on 2025-03-18 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuffle', '0005_auto_20240621_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='tokenRequestTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
